### ISSUE TITLE
Plot of Lattice 

### ISSUE THREAD

**Issue by Yaraslaut** [Quantum-Many-Body/QuantumLattices.jl#28]
It seams that at the moment it is impossible to plot Lattice, is there any plans to add this to the package ?

**Comment by waltergu** [comment]
> It seams that at the moment it is impossible to plot Lattice, is there any plans to add this to the package ?

Sorry for the late reply. In fact, it is possible to plot a lattice by using the plot function exported by Plots.jl at present: `plot(lattice::Lattice, neighbors::Int)`. You need to specify an extra positional parameter `neighbor` to indicate the orders of nearest neighbors to be plotted.
