### ISSUE TITLE
Plot of lattice is incorrect

### ISSUE THREAD

**Issue by Yaraslaut** [Quantum-Many-Body/QuantumLattices.jl#29]
Hi, 
I was trying to plot some simple lattices, such as
` l =  Lattice((0.0, 0.0), (0.5, 0.5); vectors=[[1.0, 0.0], [0.0, 1.0]], name=:Square) `
with 
`plot(l,4)`
And I see following picture 
![image](https://github.com/Quantum-Many-Body/QuantumLattices.jl/assets/44506630/41f82713-867a-418c-a784-192a372587d8)

**Comment by waltergu** [comment]
> Hi, I was trying to plot some simple lattices, such as `l = Lattice((0.0, 0.0), (0.5, 0.5); vectors=[[1.0, 0.0], [0.0, 1.0]], name=:Square)` with `plot(l,4)` And I see following picture ![image](https://user-images.githubusercontent.com/44506630/243973685-41f82713-867a-418c-a784-192a372587d8.png)

This is the "correct" picture of the lattice you just defined. Of course some explanations are needed: The small blue solid circles are the two points of the lattice in the unit cell, and

**Comment by waltergu** [comment]
To get an ordinary view of the bonds on a finite lattice, you should not use a lattice that is defined only in a unit cell with periodic boundary conditions such as
```
Lattice((0.0, 0.0), (0.5, 0.5); vectors=[[1.0, 0.0], [0.0, 1.0]])
```
This kind of lattice is a representation of the infinite translation-invariant lattice.

On the contrary, it is recommended to define a lattice containing several unit cells with the open boundary condition:
```
# construct the unit cell first
unitcell = Lattice((0.0, 0.0); vectors=[[1.0, 0.0], [0.0, 1.0]], name=:Square)

# construct a finite lattice containing several unit cells with the open boundary condition
finitelattice = Lattice(unitcell, (4, 4))
```
Then the plot of this finite lattice would be just fine:
```
plot(finitelattice, 2)
```
![lattice](https://github.com/Quantum-Many-Body/QuantumLattices.jl/assets/9401967/3bff96d5-8ea1-4f8b-ba22-d0b03707d0aa)
