### ISSUE TITLE
How to construct a two site Hubbard model hamiltonian

### ISSUE THREAD

**Issue by GiggleLiu** [Quantum-Many-Body/QuantumLattices.jl#4]
Cool project.

I wonder if it is possible to obtain the matrix representation for a two site Hubbard model with `QuantumLattices.jl`?
Although this issue is not related to "lattices".

**Comment by waltergu** [comment]
> Cool project.
> 
> I wonder if it is possible to obtain the matrix representation for a two site Hubbard model with `QuantumLattices.jl`?
> Although this issue is not related to "lattices".

Thanks for your interest in the project.

Indeed, getting the matrix representation for the Hamiltonian of a quantum many body system is beyond the goals of this package. I recommend another package **[ExactDiagonalization.jl](https://github.com/Quantum-Many-Body/ExactDiagonalization.jl)** (although still under development, but may publish its first release in a couple of days)  to achieve such a goal.
