### ISSUE TITLE
Test fails then hangs

### ISSUE THREAD

**Issue by Keno** [Quantum-Many-Body/QuantumLattices.jl#5]
I'm looking through PkgEval results and seeing a timeout on QuantumLattices. Locally, I see the following test failure, followed by a hang:
```
FunctionFactory: Test Failed at /home/keno/.julia/packages/QuantumLattices/9eivC/test/Prerequisites/Factories.jl:121
  Expression: ff.body == Block($(Expr(:quote, quote
    choice(x, y)
end)))
   Evaluated: Block(
  body: Any[:(#= /home/keno/.julia/packages/QuantumLattices/9eivC/test/Prerequisites/Factories.jl:115 =#), :(choice(x, y))]
) == Block(
  body: Any[:(choice(x, y))]
)
Stacktrace:
 [1] top-level scope at /home/keno/.julia/packages/QuantumLattices/9eivC/test/Prerequisites/Factories.jl:121
 [2] top-level scope at /home/keno/julia-old/usr/share/julia/stdlib/v1.3/Test/src/Test.jl:1113
 [3] top-level scope at /home/keno/.julia/packages/QuantumLattices/9eivC/test/Prerequisites/Factories.jl:107
```
This is on master. I suspect the package may have to be made robust to LineNumberNode parsing differences.

**Comment by waltergu** [comment]
@Keno Thank you for reporting this bug.  I'm gonna fix it soon.

**Comment by Keno** [comment]
I don't know if the hanging behavior is related to the test failure, but in either case, it would be good if the test suite didn't hang, even if the tests fail to account for that properly in PkgEval.

**Comment by waltergu** [comment]
> I don't know if the hanging behavior is related to the test failure, but in either case, it would be good if the test suite didn't hang, even if the tests fail to account for that properly in PkgEval.

Sorry for the late reply.. It seems that in my development environment (Win10+Julia1.1.1), the test process does not hang when some tests fail. Maybe you just need to wait for the other tests to complete? There are more than 1000 tests in total in this package and it takes several minutes to run all the these tests.
